name: Dashboard Data Update

# This workflow is triggered on a cron schedule based on the develop branch's
# version of the workflow. This is what performs the automatic updates.
# We also have this triggered by pushes to the branch feature/automatic-data-update,
# so that as we develop changes to the data update workflow we can push to that
# branch and see it in action.
on:
  push:
    branches:
      - feature/automatic-data-update
  schedule:
    - cron: "30 * * * *"

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          path: 'clone_dir'

      - name: Update data
        uses: ./.github/actions/update-data
        with:
          dataprocDirectory: /github/workspace/clone_dir/data-processing
          googleapi_refresh_token: ${{ secrets.GOOGLEAPI_REFRESH_TOKEN }}
          googleapi_client_id: ${{ secrets.GOOGLEAPI_CLIENT_ID }}
          googleapi_client_secret: ${{ secrets.GOOGLEAPI_CLIENT_SECRET }}

      - name: Commit any data changes
        id: commit_changes
        run: |
          ./.github/actions/scripts/commit-data-update-changes.sh clone_dir data/update

      - name: Push data update to repository
        uses: ad-m/github-push-action@v0.5.0
        if: steps.commit_changes.outputs.status == 'CHANGED'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: data/update
          directory: clone_dir
          force: true

      - name: Install JS Actions dependencies
        if: steps.commit_changes.outputs.status == 'CHANGED' || steps.commit_changes.outputs.status == 'CHANGES_ALREADY_PUSHED'
        run: |
          pushd ./.github/actions/data-update-pr
          npm ci
          popd
          pushd ./.github/actions/merge-pr
          npm ci
          popd
      - name: Data Update Pull Request
        id: pull-request
        if: steps.commit_changes.outputs.status == 'CHANGED' || steps.commit_changes.outputs.status == 'CHANGES_ALREADY_PUSHED'
        uses: ./.github/actions/data-update-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          makeComment: ${{ steps.commit_changes.outputs.status == 'CHANGED' }}
          dataUpdateBranch: azavea:data/update

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-netlify
        if: steps.commit_changes.outputs.status == 'CHANGED' || steps.commit_changes.outputs.status == 'CHANGES_ALREADY_PUSHED'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Redirect rules
          ref: data/update
          timeoutSeconds: 1000

      - name: Merge PR if passing Netlify
        if: steps.wait-for-netlify.outputs.conclusion == 'success'
        uses: ./.github/actions/merge-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ steps.pull-request.outputs.pull_number }}

      - name: Fail if PR fails Netlify
        if: steps.wait-for-netlify.outputs.conclusion == 'failure'
        run:
          exit 1
